name: Build LaTeX document 2 pdf
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: hello.tex
      - uses: actions/upload-artifact@v3
        with:
          name: hello.pdf
          path: hello.pdf
          
      - name: Commit 
        run: |
          git config --global user.name nobourge
          git config --global user.email 'nobourge@users.noreply.github.com'
          git commit -am "Automated report"
          git push
