name: latex-pandoc-jpg
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          root_file: hello.tex
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker://pandoc/core:2.9
        with:
          args: >-
            -s hello.tex
            -f latex
            -t docx
            -o hello.jpg
      - uses: actions/upload-artifact@master
        with:
          name: hello.jpg
          path: hello.jpg
