
name: LaTeX-pandoc-pdf
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: hello.tex
      - uses: actions/upload-artifact@v3
        with:
          name: hello-dl
          path: hello-dl.pdf
      - uses: actions/download-artifact@v3
        with:
          name: hello-dl
          path: hello-dl.pdf
          
